// This file was automatically generated by DependoBuf.
// Please do not change it.

using System;
using System.Collections.Generic;

class dbuf {

public class Sum {
	public readonly int a;

	public Sum(int a_) {
		a = a_;
	}

	public bool Check() {
		return true;
	}
}

public class Foo {
	public readonly int a;
	public readonly int b;
	public Sum sum;

	public Foo(int a_, int b_) {
		a = a_;
		b = b_;
		sum = new Sum((-a + b));
	}

	public bool Check() {
		return true;
	}
}

public class Sum_a {

	public Sum_a() {
	}

	public bool Check(int a) {
		return true;
	}
}

public class Foo_a_b {
	public Sum_a sum;

	public Foo_a_b() {
	}

	public bool Check(int a, int b) {
		return true && sum.Check((-a + b));
	}
}

public class Foo_b {
	public readonly int a;
	public Sum_a sum;

	public Foo_b(int a_) {
		a = a_;
	}

	public bool Check(int b) {
		return true && sum.Check((-a + b));
	}
}

public class Bar {
	public readonly int c;
	public readonly string s;
	public int e;
	public int d;
	public Foo_a_b f;
	public Foo_b g;

	public Bar(int c_, string s_) {
		c = c_;
		s = s_;
		g = new Foo_b(c);
	}

	public bool Check() {
		return true && g.Check((e + d)) && f.Check(e, d);
	}
}

public class Kek {
	public readonly int a;
	public readonly int b;
	public readonly Foo f;
	public Bar bar;

	public Kek(int a_, int b_, Foo f_) {
		a = a_;
		b = b_;
		f = f_;
		bar = new Bar(a, "qwe");
	}

	public bool Check() {
		return true;
	}
}

}

