// This file was automatically generated by DependoBuf.
// Please do not change it.

using System;
using System.Collections.Generic;

class dbuf {

public class First {
	public readonly int a;
	public readonly int b;
	public int a1;
	public bool b1;

	public First(int a_, int b_) {
		a = a_;
		b = b_;
	}

	public bool Check() {
		return true;
	}
}

public class Second {
	public readonly int a;
	public readonly int b;
	public bool a2;
	public int b2;

	public Second(int a_, int b_) {
		a = a_;
		b = b_;
	}

	public bool Check() {
		return true;
	}
}

public class Third {
	public readonly int a;
	public readonly int b;
	public string a3;
	public string b3;

	public Third(int a_, int b_) {
		a = a_;
		b = b_;
	}

	public bool Check() {
		return true;
	}
}

public class Dependent_Third {
	public readonly int a;
	public readonly int b;
	public dynamic value;

	public Dependent_Third(int a_, int b_) {
		a = a_;
		b = b_;
	}
	public bool Check() {
		return false || (value is Third) && value.Check() && value.a == a && value.b == b;
	}
}

public class First_1_b {
	public readonly int a;
	public int a1;
	public bool b1;

	public First_1_b(int a_) {
		a = a_;
	}

	public bool Check(int b) {
		return true;
	}
}

public class Second_2_b {
	public readonly int a;
	public bool a2;
	public int b2;

	public Second_2_b(int a_) {
		a = a_;
	}

	public bool Check(int b) {
		return true;
	}
}

public class Third_3_b {
	public readonly int a;
	public string a3;
	public string b3;

	public Third_3_b(int a_) {
		a = a_;
	}

	public bool Check(int b) {
		return true;
	}
}

public class Dependent_b {
	public readonly int a;
	private dynamic _value;

	public dynamic Value {
		get { return _value; }
		set { _value = value; }
	}


	public Dependent_b(int a_) {
		a = a_;
	}

	public bool Check(int b) {
		if (_value is null) {
			return false;
		}
		if (a == 5)
			return ((_value is First_1_b) && _value.Check(b));
		else if (b == 1)
			return ((_value is Second_2_b) && _value.Check(b));
		else 
			return ((_value is Third_3_b) && _value.Check(b));
		return false;
	}
}

public class First_1_a_b {
	public int a1;
	public bool b1;

	public First_1_a_b() {
	}

	public bool Check(int a, int b) {
		return true;
	}
}

public class Second_2_a_b {
	public bool a2;
	public int b2;

	public Second_2_a_b() {
	}

	public bool Check(int a, int b) {
		return true;
	}
}

public class Third_3_a_b {
	public string a3;
	public string b3;

	public Third_3_a_b() {
	}

	public bool Check(int a, int b) {
		return true;
	}
}

public class Dependent_a_b {
	private dynamic _value;

	public dynamic Value {
		get { return _value; }
		set { _value = value; }
	}


	public Dependent_a_b() {
	}

	public bool Check(int a, int b) {
		if (_value is null) {
			return false;
		}
		if (a == 5)
			return ((_value is First_1_a_b) && _value.Check(a, b));
		else if (b == 1)
			return ((_value is Second_2_a_b) && _value.Check(a, b));
		else 
			return ((_value is Third_3_a_b) && _value.Check(a, b));
		return false;
	}
}

public class Now {
	public readonly int a;
	public readonly int b;
	public int c;
	public Dependent_b d1;
	public Dependent_a_b d2;

	public Now(int a_, int b_) {
		a = a_;
		b = b_;
		d1 = new Dependent_b((a + b));
	}

	public bool Check() {
		return true && d2.Check(c, (c + c)) && d1.Check((c + b));
	}
}

}

