// This file was automatically generated by DependoBuf.
// Please do not change it.

using System;
using System.Collections.Generic;

class dbuf {

public class SimpleMessageDep {
	public readonly int a;

	public SimpleMessageDep(int a_) {
		a = a_;
	}

	public bool Check() {
		return true;
	}
}

public class SimpleMessageFields {
	public int a;
	public int b;

	public SimpleMessageFields() {
	}

	public bool Check() {
		return true;
	}
}

public class SimpleMessageDepFields {
	public readonly SimpleMessageFields simpleMessageFields;
	public int i;
	public uint u;
	public string s;
	public float f;
	public bool b;

	public SimpleMessageDepFields(SimpleMessageFields simpleMessageFields_) {
		simpleMessageFields = simpleMessageFields_;
	}

	public bool Check() {
		return true;
	}
}

public class TestingSimpleMessage {
	public SimpleMessageDep simpleMessageDep;
	public SimpleMessageDepFields simpleMessageDepFields;

	public TestingSimpleMessage() {
		simpleMessageDep = new SimpleMessageDep(((1 + 3) + (5 - 4)));
		simpleMessageDepFields = new SimpleMessageDepFields(new SimpleMessageFields{a = 5, b = 6});
	}

	public bool Check() {
		return true;
	}
}

}

