# This file was automatically generated by DependoBuf.
# Please do not change it.

from dataclasses import dataclass


@dataclass
class Address:
  id: int | None = None
  street: str | None = None
  floor: int | None = None
  withIntercom: bool | None = None


@dataclass
class Pet:
  id: int | None = None
  kind: str | None = None
  name: str | None = None


@dataclass
class User:
  id: int | None = None
  name: str | None = None
  address: Address | None = None
  pet: Pet | None = None
