# This file was automatically generated by DependoBuf.
# Please do not change it.

from dataclasses import dataclass


@dataclass
class Address:
  id: int
  street: str
  floor: int
  withIntercom: bool


@dataclass
class Pet:
  id: int
  kind: str
  name: str


@dataclass
class User:
  id: int
  name: str
  address: Address
  pet: Pet
  money: float
