site_name: DependoBuf
repo_name: DependoBuf
repo_url: https://github.com/sphericalpotatoinvacuum/DependoBuf
edit_uri_template: 'blob/main/docs/{path}'
copyright: Copyright &copy; 2023 Alexander Bogdanov, Alice Vernigor

nav:
- Introduction: index.md
- Lexical Structure:
  - lexical-structure/index.md
  - lexical-structure/notation.md
  - lexical-structure/keywords.md
  - lexical-structure/identifiers.md
  - lexical-structure/values.md
- expressions.md
- messages.md
- enums.md

theme:
  name: material
  icon:
    logo: material/book
    repo: simple/github
  favicon: assets/logo.png
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  features:
    - navigation.path
    - navigation.top
    - navigation.indexes
    - content.code.annotate

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
