#![allow(unused_variables, unused_imports, unused_parens, dead_code)]
//! This file was automatically generated by DependoBuf

pub struct ComplexDependenciesBool {
}

impl ComplexDependenciesBool {
    pub fn check(&self, b1: bool, b2: bool, v7: &std::rc::Rc<Field>, v8: &std::rc::Rc<Field>, v9: &std::rc::Rc<Field>) -> bool {
        return true;
    }
}

