#![allow(unused_variables, unused_imports, unused_parens, dead_code)]
//! This file was automatically generated by DependoBuf

pub struct ComplexDFieldsArithmetic {
    pub n: i64,
    pub m: i64,
    pub f1: std::rc::Rc<Field1>,
    pub f2: std::rc::Rc<Field2>,
    pub f3: std::rc::Rc<Field3>,
    pub f4: std::rc::Rc<Field4>,
    pub f5: std::rc::Rc<Field5>,
}

impl ComplexDFieldsArithmetic {
    pub fn check(&self) -> bool {
        let n = self.n;
        let m = self.m;
        let f1 = &self.f1;
        let f2 = &self.f2;
        let f3 = &self.f3;
        let f4 = &self.f4;
        let f5 = &self.f5;
        if !f1.check() { return false; }
        if !f2.check() { return false; }
        if !f3.check() { return false; }
        if !f4.check() { return false; }
        if !f5.check() { return false; }
        return true;
    }
}

