#![allow(unused_variables, unused_imports, unused_parens, dead_code)]
//! This file was automatically generated by DependoBuf

pub struct ComplexDependenciesArithmetic {
}

impl ComplexDependenciesArithmetic {
    pub fn check(&self, n: i64, m: i64, f1: &std::rc::Rc<Field1>, f2: &std::rc::Rc<Field2>, f3: &std::rc::Rc<Field3>, f4: &std::rc::Rc<Field4>, f5: &std::rc::Rc<Field5>) -> bool {
        return true;
    }
}

