#![allow(unused_variables, unused_imports, unused_parens, dead_code)]
//! This file was automatically generated by DependoBuf

pub struct ComplexFieldsAllTypes {
    pub n: i64,
    pub m: i64,
    pub f1: std::rc::Rc<Field1>,
    pub f2: std::rc::Rc<Field2>,
    pub f3: std::rc::Rc<Field3>,
    pub f4: std::rc::Rc<Field4>,
    pub f5: std::rc::Rc<Field5>,
    pub b1: bool,
    pub b2: bool,
    pub v7: std::rc::Rc<Field>,
    pub v8: std::rc::Rc<Field>,
    pub v9: std::rc::Rc<Field>,
}

impl ComplexFieldsAllTypes {
    pub fn check(&self) -> bool {
        let n = self.n;
        let m = self.m;
        let f1 = &self.f1;
        let f2 = &self.f2;
        let f3 = &self.f3;
        let f4 = &self.f4;
        let f5 = &self.f5;
        let b1 = self.b1;
        let b2 = self.b2;
        let v7 = &self.v7;
        let v8 = &self.v8;
        let v9 = &self.v9;
        if !f1.check() { return false; }
        if !f2.check() { return false; }
        if !f3.check() { return false; }
        if !f4.check() { return false; }
        if !f5.check() { return false; }
        if !v7.check() { return false; }
        if !v8.check() { return false; }
        if !v9.check() { return false; }
        return true;
    }
}

