#![allow(unused_variables, unused_imports, unused_parens, dead_code)]
//! This file was automatically generated by DependoBuf

pub struct ComplexDependencies {
}

impl ComplexDependencies {
    pub fn check(&self, n: &std::rc::Rc<Nat>, v: &std::rc::Rc<Vec>) -> bool {
        return true;
    }
}

