#![allow(unused_variables, unused_imports, unused_parens, dead_code)]
//! This file was automatically generated by DependoBuf

pub struct ComplexFieldsBool {
    pub n: i64,
    pub m: i64,
    pub b1: bool,
    pub b2: bool,
    pub v7: std::rc::Rc<Field>,
    pub v8: std::rc::Rc<Field>,
    pub v9: std::rc::Rc<Field>,
}

impl ComplexFieldsBool {
    pub fn check(&self) -> bool {
        let n = self.n;
        let m = self.m;
        let b1 = self.b1;
        let b2 = self.b2;
        let v7 = &self.v7;
        let v8 = &self.v8;
        let v9 = &self.v9;
        if !v7.check() { return false; }
        if !v8.check() { return false; }
        if !v9.check() { return false; }
        return true;
    }
}

