#![allow(unused_variables, unused_imports, unused_parens, dead_code)]
//! This file was automatically generated by DependoBuf

pub enum ConstructorsWithFields {
    Constructor1{
        f1: std::rc::Rc<Field1>,
    },
    Constructor2{
        f2: std::rc::Rc<Field2>,
        f3: std::rc::Rc<Field3>,
    },
    Constructor3{
        f4: std::rc::Rc<Field4>,
        f5: std::rc::Rc<Field5>,
    },
}
use ConstructorsWithFields::*;

impl ConstructorsWithFields {
    pub fn check(&self) -> bool {
        match self {
            Constructor1 { f1 } => {
                if !f1.check() { return false; }
            }
            Constructor2 { f2, f3 } => {
                if !f2.check() { return false; }
                if !f3.check() { return false; }
            }
            Constructor3 { f4, f5 } => {
                if !f4.check() { return false; }
                if !f5.check() { return false; }
            }
        }
        return true;
    }
}

