#![allow(unused_variables, unused_imports, unused_parens, dead_code)]
//! This file was automatically generated by DependoBuf

pub struct EmptyMessage {
}

impl EmptyMessage {
    pub fn check(&self) -> bool {
        return true;
    }
}

