#![allow(unused_variables, unused_imports, unused_parens, dead_code)]
//! This file was automatically generated by DependoBuf

pub struct FieldsDependOnDependenciesArithmetic {
    pub f1: std::rc::Rc<Field1>,
    pub f2: std::rc::Rc<Field2>,
    pub f3: std::rc::Rc<Field3>,
    pub f4: std::rc::Rc<Field4>,
    pub f5: std::rc::Rc<Field5>,
}

impl FieldsDependOnDependenciesArithmetic {
    pub fn check(&self, n: i64, m: i64) -> bool {
        let f1 = &self.f1;
        let f2 = &self.f2;
        let f3 = &self.f3;
        let f4 = &self.f4;
        let f5 = &self.f5;
        if !f1.check() { return false; }
        if !f2.check() { return false; }
        if !f3.check() { return false; }
        if !f4.check() { return false; }
        if !f5.check() { return false; }
        return true;
    }
}

