#![allow(unused_variables, unused_imports, unused_parens, dead_code)]
//! This file was automatically generated by DependoBuf

pub enum MultipleDependenciesPatternMatching {
    Constructor1,
    Constructor2,
    Constructor3,
    Constructor4,
    Constructor5,
    Constructor6,
}
use MultipleDependenciesPatternMatching::*;

impl MultipleDependenciesPatternMatching {
    pub fn check(&self, n: &std::rc::Rc<Nat>, m: &std::rc::Rc<Nat>) -> bool {
        match self {
            Constructor1 {  } => {
            }
            Constructor2 {  } => {
            }
            Constructor3 {  } => {
            }
            Constructor4 {  } => {
            }
            Constructor5 {  } => {
            }
            Constructor6 {  } => {
            }
        }
        return true;
    }
}

