#![allow(unused_variables, unused_imports, unused_parens, dead_code)]
//! This file was automatically generated by DependoBuf

pub struct SimpleFields {
    pub i: i64,
    pub b: bool,
    pub s: std::rc::Rc<String>,
}

impl SimpleFields {
    pub fn check(&self) -> bool {
        let i = self.i;
        let b = self.b;
        let s = &self.s;
        return true;
    }
}

