#![allow(unused_variables, unused_imports, unused_parens, dead_code)]
//! This file was automatically generated by DependoBuf

pub struct SimpleDependenciesField {
    pub i: i64,
    pub v1d: std::rc::Rc<Vec>,
    pub v2d: std::rc::Rc<Vec>,
}

impl SimpleDependenciesField {
    pub fn check(&self) -> bool {
        let i = self.i;
        let v1d = &self.v1d;
        let v2d = &self.v2d;
        if !v1d.check() { return false; }
        if !v2d.check() { return false; }
        return true;
    }
}

