#![allow(unused_variables, unused_imports, unused_parens, dead_code)]
//! This file was automatically generated by DependoBuf

pub struct SimpleDependencies {
}

impl SimpleDependencies {
    pub fn check(&self, i: i64, s: &std::rc::Rc<String>, b: bool) -> bool {
        return true;
    }
}

