#![allow(unused_variables, unused_imports, unused_parens, dead_code)]
//! This file was automatically generated by DependoBuf

pub struct C {
    pub a: std::rc::Rc<A>,
    pub b: std::rc::Rc<B>,
}

pub struct B {
    pub f: i64,
}

pub struct A {
}

impl C {
    pub fn check(&self) -> bool {
        let a = &self.a;
        let b = &self.b;
        if !a.check(((1 + 3) + (5 - 4))) { return false; }
        if !b.check(&a) { return false; }
        return true;
    }
}

impl B {
    pub fn check(&self, a: &std::rc::Rc<A>) -> bool {
        let f = self.f;
        return true;
    }
}

impl A {
    pub fn check(&self, n: i64) -> bool {
        return true;
    }
}

