#![allow(unused_variables, unused_imports, unused_parens, dead_code)]
//! This file was automatically generated by DependoBuf

pub enum SimpleConstructors {
    Constructor1,
    Constructor2,
    Constructor3,
}
use SimpleConstructors::*;

impl SimpleConstructors {
    pub fn check(&self, n: &std::rc::Rc<Nat>) -> bool {
        match self {
            Constructor1 {  } => {
            }
            Constructor2 {  } => {
            }
            Constructor3 {  } => {
            }
        }
        return true;
    }
}

