package dbuf

// This file is autogenerated. Please, do not change it manually.

class Kek(val i: Long) {
    var j: Long = 0

    fun check() {
    }
}

class Constructor1(val n: Long, val m: Long, val k: Kek) {
    fun check() {
    }
}

class Constructor2(val n: Long, val m: Long, val k: Kek) {
    var x: Long = 0

    fun check() {
    }
}

class Constructor3(val n: Long, val m: Long, val k: Kek) {
    var y: Long = 0
    lateinit var k1: Kek
    lateinit var k2: Kek

    fun check() {
        check(this::k1.isInitialized) {"property k1 should be initialized"}
        check(this::k2.isInitialized) {"property k2 should be initialized"}

        check(k1.i == (y + n)) {"dependency i of k1 (is ${k1.i}) should be ${(y + n)}"}
        check(k2.i == ((k.j + k1.j) + m)) {"dependency i of k2 (is ${k2.i}) should be ${((k.j + k1.j) + m)}"}
    }
}

class Constructor4(val n: Long, val m: Long, val k: Kek) {
    fun check() {
    }
}

class Constructor5(val n: Long, val m: Long, val k: Kek) {
    fun check() {
    }
}

class Constructor7(val n: Long, val m: Long, val k: Kek) {
    fun check() {
    }
}

class Constructor8(val n: Long, val m: Long, val k: Kek) {
    fun check() {
    }
}

class Pair(val n: Long, val m: Long, val k: Kek){
    lateinit var inside: Any

    fun check() {
        check(k.i == (m + (m * m))) {"dependency i of k (is ${k.i}) should be ${(m + (m * m))}"}

        check(this::inside.isInitialized) {"property inside should be initialized"}

        if (n == 1L) {
            if (inside is Constructor1) {
                (inside as Constructor1).check()
            }
            else {
                check(false) {"not valid inside"}
            }
            return
        }
        if (n == 2L && m == 2L) {
            if (inside is Constructor2) {
                (inside as Constructor2).check()
            }
            else if (inside is Constructor3) {
                (inside as Constructor3).check()
            }
            else {
                check(false) {"not valid inside"}
            }
            return
        }
        if (m == 3L) {
            if (inside is Constructor4) {
                (inside as Constructor4).check()
            }
            else if (inside is Constructor5) {
                (inside as Constructor5).check()
            }
            else {
                check(false) {"not valid inside"}
            }
            return
        }
        if (n == 4L && m == -4L) {
            check(false) {"not valid inside"}
            return
        }
        if (true) {
            if (inside is Constructor7) {
                (inside as Constructor7).check()
            }
            else {
                check(false) {"not valid inside"}
            }
            return
        }
        if (n == 4L) {
            if (inside is Constructor8) {
                (inside as Constructor8).check()
            }
            else {
                check(false) {"not valid inside"}
            }
            return
        }
    }
}

