# This file was automatically generated by DependoBuf.
# Please do not change it.

from __future__ import annotations

from annotated_types import Ge
from dataclasses import dataclass
from typing import Annotated

Unsigned = Annotated[int, Ge(0)]


class DbufError(TypeError):
    pass


class User:
    @dataclass
    class __User:
        id: int
        name: str
        f: float

        def check(self) -> None:
            pass

    user_type = __User

    def __init__(self) -> None:
        self.dependencies = ()

    def construct(self, id: int, name: str, f: float) -> __User:
        obj = self.__User(id, name, f)
        obj.check(*self.dependencies)
        return obj


def _is_consistent(actual: tuple, expected: tuple) -> bool:
    for i in range(len(actual)):
        if expected[i] is None:
            continue

        if actual[i] != expected[i]:
            return False

    return True
