#include "core/codegen/rust_gen.h"

#include "core/codegen/rust_check_gen.h"
#include "core/codegen/rust_struct_gen.h"

namespace dbuf::gen {
void RustCodeGenerator::Generate(ast::AST *tree) {
  if (tree == nullptr) {
    std::cerr << "Rust codegen did\'t get AST" << std::endl;
    return;
  }
  *output_ << "// This file was automatically generated by DependoBuf\n\n";
  RustStructGenerator(*output_, *tree).Generate();
  RustCheckGenerator(*output_, *tree).Generate();
}
} // namespace dbuf::gen