#include "core/codegen/kotlin_target/kotlin_printer.h"

namespace dbuf::gen::kotlin {

const std::string_view Printer::kDontChangeMessage = "This file is autogenerated. Please, do not change it manually.";
const std::string_view Printer::kPackageName       = "dbuf";
const unsigned int Printer::kIndentLength          = 4;

Printer::Printer(std::shared_ptr<std::ostream> output)
    : output_(std::move(output)) {
  *output_ << "package " << kPackageName << "\n\n";
  *output_ << "// " << kDontChangeMessage << "\n\n";
  need_indent_ = true;
}

void Printer::AddIndent() {
  ++indent_count_;
}

void Printer::RemoveIndent() {
  --indent_count_;
}

void Printer::NewLine() {
  *output_ << "\n";
  need_indent_ = true;
}

Scope::Scope(Printer &printer)
    : printer_(printer)
    , ended_(false) {}
void Scope::Close() {
  if (ended_) {
    return;
  }
  End();
  ended_ = true;
}

} // namespace dbuf::gen::kotlin
