#pragma once

#include <iostream>
#include <string>

namespace dbuf::gen {

static const std::string kReadme = "// This file was automatically generated by DependoBuf.\n"
                                   "// Please do not change it.\n";

static const std::string kIncludedLibraries = "using System;\n"
                                              "using System.Collections.Generic;\n";

static const std::string kOpenNamespace = "class dbuf {\n";

static const std::string kCloseNamespace = "}\n";

static const std::string kBaseEnumFields = "\tpublic dynamic value;\n\n";

} // namespace dbuf::gen
