name: Run code checks

on:
  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/ci.yml"
      - "lib/**"
      - "src/**"
      - "test/**"
      - "CMakeLists.txt"
      - ".clang-*"


env:
  BUILD_TYPE: Release

jobs:
  tidy:
    name: Check codestyle using clang-tidy
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Set outputs
      id: vars
      run: |
        echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
        echo "date=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_OUTPUT
        echo "ref=${{ github.event_name == 'pull_request' && github.event.number || github.ref }}" >> $GITHUB_OUTPUT

    - name: cache
      uses: actions/cache@v4
      with:
        path: ${{ github.workspace }}/.ccache
        key: ccache-tidy-${{ env.BUILD_TYPE }}-${{ steps.vars.outputs.ref }}-${{ steps.vars.outputs.sha_short }}-${{ steps.vars.outputs.date }}
        restore-keys: |
          ccache-tidy-${{ env.BUILD_TYPE }}-${{ steps.vars.outputs.ref }}-
          ccache-tidy-${{ env.BUILD_TYPE }}-

    - name: clang-tidy review
      id: review
      env:
        CC: clang-16
        CXX: clang++-16
        CCACHE_BASEDIR: /github/workspace
        CCACHE_DIR: /github/workspace/.ccache
        CCACHE_SLOPPINESS: file_macro,time_macros
        CCACHE_NOHASHDIR: true
      uses: ZedThree/clang-tidy-review@v0.17.0
      with:
        apt_packages: libfl-dev,flex,bison,clang-16,libc++-16-dev,libc++abi-16-dev,ccache
        clang_tidy_version: 16
        cmake_command: >
          cmake -B /github/workspace/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -D CMAKE_C_COMPILER_LAUNCHER=ccache -D CMAKE_CXX_COMPILER_LAUNCHER=ccache &&
          cmake --build /github/workspace/build --target dbuf &&
          ccache -s
        build_dir: /github/workspace/build
        config_file: .clang-tidy
        include: '*.h,*.cc'

    - if: steps.review.outputs.total_comments > 0
      name: Fail if there are requested changes
      run: exit 1

  format:
    name: Format the code using clang-format
    permissions: write-all
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ${{github.workspace}}

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Format
      uses: DoozyX/clang-format-lint-action@v0.16.1
      with:
        source: 'lib src test'
        exclude: ''
        extensions: 'h,cc'
        clangFormatVersion: 16
        inplace: True

    - name: Suggest
      uses: getsentry/action-git-diff-suggestions@main
      with:
        message: 'clang-format suggested changes'

    - name: Fail if changes
      run: git diff --exit-code
